using System.Windows.Input;

namespace InvertedPendulumTransporterPhysics.Controllers
{
    /// <summary>
    /// Interface dedicated to game controller
    /// </summary>
    public interface IGameController : IController
    {
        /// <summary>
        /// Target pendulum angle generated by user in X-coordintate
        /// </summary>
        double UserAngleX { get; }

        /// <summary>
        /// Target pendulum angle generated by user in Y-coordintate
        /// </summary>
        double UserAngleY { get; }

        /// <summary>
        /// Game mode enablement
        /// </summary>
        bool GameEnabled { get; set; }

        /// <summary>
        /// Game progress enablement
        /// </summary>
        bool GamePlaying { get; set; }

        /// <summary>
        /// User actions handlers
        /// </summary>
        /// <param name="key">Keyboard key</param>
        void HandleKey(Key key);
    }
}
